version: '3.8'

services:
  postgres_for_bot:
    restart: always
    image: postgres
    container_name: postgres_container
    expose:
      - 5432
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data
      - postgres_config:/etc/postgresql
    logging:
      options:
        max-size: 50m

  redis_for_bot:
    restart: always
    image: redis
    container_name: redis_container
    volumes:
      - redis-data:/data
    expose:
      - 6379
    env_file:
      - .env
    sysctls:
      - net.core.somaxconn=1024
    command: redis-server --requirepass ${REDIS_PASSWORD}
    logging:
      options:
        max-size: 50m

  bot:
    restart: always
    build:
      context: ../.
      dockerfile: docker/bot.Dockerfile
    container_name: src
    depends_on:
      - postgres_for_bot
      - redis_for_bot
    command: uvicorn main:app --workers 4 --host 0.0.0.0 --port 8080
    ports:
      - "8080:8080"
    env_file:
      - .env
    logging:
      options:
        max-size: 50m
# TODO add service proxy (nginx)
volumes:
  postgres:
  postgres_config:
  redis-data: