version: '3.8'

services:
  postgres_for_bot:
    restart: always
    image: postgres
    container_name: postgres_container
    environment:
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data
      - postgres_config:/etc/postgresql

  redis_for_bot:
    restart: always
    image: redis
    container_name: redis_container
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"
    env_file:
      - .env
    sysctls:
      - net.core.somaxconn=1024
    command:
      redis-server --requirepass ${REDIS_PASSWORD}

  # use ngrok for local test webhook
  ngrok:
    image: ngrok/ngrok:latest
    restart: always
    network_mode: "host"
    environment:
      NGROK_AUTHTOKEN: ${NGROK_AUTHTOKEN}
    command: http 8080 --domain=${DOMAIN}
#    to use custom config
#    command: start --all --config /etc/ngrok.yml
#    volumes:
#      - ./ngrok/ngrok.yml:/etc/ngrok.yml
#      - ./ngrok/log/:/var/log/
    ports:
      - "4040:4040"

  bot:
    restart: always
    build:
      context: ../.
      dockerfile: docker/bot.Dockerfile
    container_name: src
    depends_on:
      - postgres_for_bot
      - redis_for_bot
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8080
    volumes:
      - ../src/:/app/
    ports:
      - "8080:8080"
    env_file:
      - .env

volumes:
  postgres:
  postgres_config:
  redis-data: